### ISSUE TITLE
报错！！！

### ISSUE THREAD

**Issue by heroPool** [youth5201314/XFrame#16]
![image](https://user-images.githubusercontent.com/26159915/28870547-43a3be50-77b3-11e7-8eae-7c93d4b9f9f7.png)

加入依赖之后总是报下面的错误
Error:Execution failed for task ':homedemobyzhu:processDebugManifest'.
> Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(26.0.0-alpha1) from [com.android.support:cardview-v7:26.0.0-alpha1] AndroidManifest.xml:24:9-38
	is also present at [com.android.support:recyclerview-v7:25.3.1] AndroidManifest.xml:24:9-31 value=(25.3.1).
	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:22:5-24:41 to override.

**Comment by youth5201314** [comment]
你用最新版的，我忘记更新文档了！

**Comment by heroPool** [comment]
最新版版本是多少咯？

**Comment by youth5201314** [comment]
你把版本号换成+或者latestVersion就可以获取最新版本
