### ISSUE TITLE
question

### ISSUE THREAD

**Issue by heroPool** [youth5201314/XFrame#17]
老哥，我的Xtoast为何如此粗大，我是使用的不是依赖，是import的module。

![image](https://user-images.githubusercontent.com/26159915/29256692-f36da510-80de-11e7-8101-33f6e5044702.png)

**Comment by youth5201314** [comment]
我测试是没有问题的，如果你是本地依赖的话，可以修改下xtoast_view布局文件，或者XToast中custom方法里LayoutInflater得到的view，手动设置高宽，最好反馈下原因，我这毕竟测试机有限，都没有问题！
