### ISSUE TITLE
一点不成熟的小建议

### ISSUE THREAD

**Issue by sweet2o09** [youth5201314/XFrame#6]
首先,很感谢你的开源项目,让我学到很多,我之前一直都只用你的banner,最近在整理所学知识点的时候发现了你的这个项目,受益匪浅,
bug:
1.XloadingDialog中弹出自定义文字(水平显示2)点击后无关闭,只能退出应用,这个小问题,我自己也可以处理,不知道是不是故意这样弄的
建议:
1.现在都喜欢仿iOS,各种仿造,就拿下拉刷新来说吧,我看很多APP都会做成iOS样式的下拉刷新,还有Dialog等.不知道你对这个趋势怎么看?是否也可以在你的这个框架里面添加点?

**Comment by youth5201314** [comment]
第一点，仔细看下demo，你就明白了（可以设置是否允许手动取消，设置成不可取消，你也可以通过代码取消，我demo不是有描述说3秒后自动消失吗？），第二点我认为市面上优秀的app不存在各种模仿ios，都是基于MD的设计规范延伸的，当然ios一些好的效果可以借鉴。但是我不会加入我的框架中，那样很累赘，这个不是所有人的喜好，自己喜欢什么效果自己加就是了，框架不是大而全，而是只用必要的功能！
